---
- name: Install required packages
  loop:
    - sudo
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  tags:
    - sudo

- name: Create defined group
  loop: "{{ sudo_groups }}"
  ansible.builtin.group:
    name: "{{ item }}"
    system: true
    state: present
  tags:
    - sudo

- name: Write sudoers config
  ansible.builtin.template:
    src: sudoers.j2
    dest: /etc/sudoers
    validate: /usr/sbin/visudo -cf %s
    owner: root
    group: root
    mode: u=r,g=r,o=
  tags:
    - sudo

...
